Added verification command for stow presence

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -42,6 +42,14 @@ setup_gitconfig () {
 
 setup_gitconfig
 
+if hash gdate 2>/dev/null; then
+  echo "Using stow to symlink configs."
+else
+  echo >&2 "I require stow but it's not installed.  Aborting."
+  exit 1
+fi
+
+
 stow awesome
 stow git
 stow sublime3
